### ISSUE TITLE
Diagnostics of the same grids do not have the same spaces

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaCore.jl#1592]
When we have multiple diagnostics from a single ClimaAtmos simulation, the diagnostics don't have the same space. For example if I do the following with the attached data from ClimaAtmos output.

```
using ClimaCore.InputOutput
filein = "diagnostics/wa_inst_400.0.h5"
reader_wa = InputOutput.HDF5Reader(filein)
wa = InputOutput.read_field(reader_wa, "wa_inst")
filein = "diagnostics/hus_inst_400.0.h5"
reader_hus = InputOutput.HDF5Reader(filein)
hus = InputOutput.read_field(reader_hus, "hus_inst")
println(axes(wa) == axes(hus))
println(axes(wa))
println(axes(hus))
```
And I got:
```
false
CenterExtrudedFiniteDifferenceSpace:
  context: SingletonCommsContext using CPUSingleThreaded
  horizontal:
    mesh: 6×6×6-element EquiangularCubedSphere of SphereDomain: radius = 6.371e6
    quadrature: 4-point Gauss-Legendre-Lobatto quadrature
  vertical:
    mesh: 10-element IntervalMesh of IntervalDomain: z ∈ [0.0,30000.0] (:bottom, :top)
CenterExtrudedFiniteDifferenceSpace:
  context: SingletonCommsContext using CPUSingleThreaded
  horizontal:
    mesh: 6×6×6-element EquiangularCubedSphere of SphereDomain: radius = 6.371e6
    quadrature: 4-point Gauss-Legendre-Lobatto quadrature
  vertical:
    mesh: 10-element IntervalMesh of IntervalDomain: z ∈ [0.0,30000.0] (:bottom, :top)
```

It would be helpful if they are on the same space, as we can manipulate the diagnostics for debugging.

[diagnostics.zip](https://github.com/CliMA/ClimaCore.jl/files/13943970/diagnostics.zip)
